---
- name: Configure local Fedora
  become_method: ansible.builtin.sudo
  hosts: all
  vars_prompt:
    - name: upgrade_firmware
      prompt: Do you want to upgrade your firmware (yes/no)?
      private: false
    - name: install_kelkoo
      prompt: Do you want to play Kelkoo role (yes/no)?
      private: false
    - name: install_vscode
      prompt: Do you want to install VS Code (yes/no)?
      private: false
  roles:
    - role: 'roles/fedora/firmware'
      when: upgrade_firmware | bool
    - role: 'roles/shell'
    - role: 'roles/fedora/kelkoo'
      when: install_kelkoo | bool
    - role: 'roles/fedora/vscode'
      when: install_vscode | bool
