---
- name: Configure local Fedora
  become_method: ansible.builtin.sudo
  hosts: all
  vars_prompt:
    - name: upgrade_firmware
      prompt: Do you want to upgrade your firmware (yes/no)?
      private: false
    - name: install_kelkoo
      prompt: Do you want to play Kelkoo role (yes/no)?
      private: false
    - name: install_vscode
      prompt: Do you want to install VS Code (yes/no)?
      private: false
    - name: install_keepass
      prompt: Do you want to install KeePass (yes/no)?
      private: false
    - name: install_jetbrains
      prompt: Do you want to install JetBrains Toolbox (for IntelliJ) (yes/no)?
      private: false
  roles:
    - role: 'firmware'
      when: upgrade_firmware | bool
    - role: 'shell'
    - role: 'webhome'
    - role: 'kelkoo'
      when: install_kelkoo | bool
    - role: 'vscode'
      when: install_vscode | bool
    - role: 'keepass'
      when: install_keepass | bool
    - role: 'jetbrains'
      when: install_jetbrains | bool
