vscode:
  extensions:
    - anthropic.claude-code
    - dvirtz.parquet-viewer
    - hediet.vscode-drawio
    - inferrinizzard.prettier-sql-vscode
    - mechatroner.rainbow-csv
    - mrmlnc.vscode-json5
    - ms-python.debugpy
    - ms-python.python
    - ms-python.vscode-pylance
    - ms-python.vscode-python-envs
    - redhat.java
    - savh.json5-kit
    - scala-lang.scala
    - scalameta.metals
    - vscjava.vscode-gradle
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-pack
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
    - wholroyd.jinja
    - yzhang.markdown-all-in-one
