---
- name: Import Microsoft key for vscode
  become: true
  ansible.builtin.rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc
- name: Added Microsoft vscode repo
  become: true
  ansible.builtin.copy:
    src: "files/vscode.repo"
    dest: "/etc/yum.repos.d/vscode.repo"
    mode: '0644'
- name: Install vscode
  become: true
  ansible.builtin.dnf:
    name: "code"
    state: latest
- name: List currently installed VS Code extensions
  ansible.builtin.command: code --list-extensions
  register: vscode_installed_extensions
  changed_when: false
- name: Install VS Code extensions
  ansible.builtin.command: "code --install-extension {{ item }}"
  loop: "{{ vscode.extensions }}"
  when: item not in vscode_installed_extensions.stdout_lines
