---
- name: Import Microsoft key for vscode
  become: true
  ansible.builtin.rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc
- name: Added Microsoft vscode repo
  become: true
  ansible.builtin.copy:
    src: "files/vscode.repo"
    dest: "/etc/yum.repos.d/vscode.repo"
    mode: '0644'
- name: Install vscode
  become: true
  ansible.builtin.dnf:
    name: "code"
    state: latest
