---
- name: Install kelkoo packages
  become: true
  ansible.builtin.dnf:
    name:
      - ca-certificates-kelkoogroup
      - kelkoo-dev-tools
      - shiva-build-scripts
      - java-21-openjdk-devel
      - discord
    state: latest
- name: Install additional firefox codec (see https://pagure.io/fedora-workstation/issue/84)
  become: true
  ansible.builtin.dnf:
    name:
      - gstreamer1-plugin-openh264
      - mozilla-openh264
    state: latest
- name: Maven
  block:
    - name: Maven - Remove conflicting if present
      become: true
      ansible.builtin.dnf:
        name:
          - maven
          - maven-lib
        state: absent
    - name: Maven - Create workdirs
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "~/.m2"
        - "~/apache-maven"
    - name: Maven - Configure Kelkoo Maven repos
      ansible.builtin.get_url:
        url: "{{ kelkoo.maven.settings }}"
        dest: "~/.m2/settings.xml"
        mode: '0644'
    - name: Maven - shell config
      ansible.builtin.copy:
        src: "files/.kelkoorc"
        dest: "~/.kelkoorc"
        mode: '0644'
    - name: Maven - shell config import
      ansible.builtin.lineinfile:
        path: "{{ item }}"
        line: "source ~/.kelkoorc"
      loop:
        - "~/.bashrc"
        - "~/.zshrc"
    - name: Maven - Download binaries
      ansible.builtin.unarchive:
        src: "{{ kelkoo.maven.package }}"
        dest: "~/apache-maven"
        remote_src: true
- name: sbt
  block:
    - name: sbt - Install sbt
      become: true
      ansible.builtin.dnf:
        name: "sbt"
        state: latest
    - name: sbt - Create config fir
      ansible.builtin.file:
        path: "~/.sbt"
        state: directory
        mode: '0755'
    - name: sbt - Add build repo override option
      become: true
      ansible.builtin.lineinfile:
        path: "/etc/sbt/sbtopts"
        line: "-Dsbt.override.build.repos=true"
    - name: sbt - Configure kelkoo sbt repos
      ansible.builtin.copy:
        src: "files/.sbt/repositories"
        dest: "~/.sbt/repositories"
        mode: '0644'
    # fixes: https://stackoverflow.com/questions/77000440/sbt-user-limit-of-inotify-instances-reached-or-too-many-open-files
    - name: sbt - Allow high fs inotify
      ansible.builtin.copy:
        src: "files/etc/sysctl.d/90-inotify.conf"
        dest: "/etc/sysctl.d/90-inotify.conf"
        mode: '0644'
      become: true
      register: inotify_setup
    - ansible.builtin.command: sysctl --system
      become: true
      when: inotify_setup.changed
- name: npm
  block:
    - name: npm - Install nodejs/npm
      become: true
      ansible.builtin.dnf:
        name: "nodejs"
        state: latest
    - name: npm - Add kelkoo repo configs
      ansible.builtin.command: "npm config set {{ item }}" # noqa: no-changed-when
      loop: "{{ kelkoo.npm.config_list }}"
- name: Python
  block:
    - name: Python - Install python-pip
      become: true
      ansible.builtin.dnf:
        name: "python3-pip"
        state: latest
    - name: Python - Create pip conf dir
      ansible.builtin.file:
        path: "~/.config/pip/"
        state: directory
        mode: '0755'
    - name: Python - Add pip config
      ansible.builtin.copy:
        src: "files/.config/pip/pip.conf"
        dest: "~/.config/pip/pip.conf"
        mode: '0644'
- name: Podman
  block:
    - name: Podman - Install podman
      become: true
      ansible.builtin.dnf:
        name:
          - podman
          - podman-docker
        state: latest
    - name: Podman - Create pip conf dir
      ansible.builtin.file:
        path: "~/.config/containers/"
        state: directory
        mode: '0755'
    - name: Podman - Add pip config
      ansible.builtin.copy:
        src: "files/.config/containers/registries.conf"
        dest: "~/.config/containers/registries.conf"
        mode: '0644'
    - name: Podman - Add symlink for test containers
      ansible.builtin.command: "systemctl --user enable podman.socket --now" # noqa: no-changed-when
- name: Kubectl
  block:
    - name: Kubectl - Add yum repo
      become: true
      ansible.builtin.copy:
        src: "files/kubernetes.repo"
        dest: "/etc/yum.repos.d/kubernetes.repo"
        mode: '0644'
    - name: Kubectl - dnf install
      become: true
      ansible.builtin.dnf:
        name: "kubectl"
        state: latest
