---
- name: Firmware mgr refresh
  ansible.builtin.command: 'fwupdmgr refresh --force' # noqa: no-changed-when
  become: true
- name: Firmware update
  ansible.builtin.command: 'fwupdmgr update' # noqa: no-changed-when
  become: true
